#!/bin/bash

# Binaries generated by CMake are located in a different place
# to those of autoconf
if [ -z $GENERATED_USING_CMAKE ]; then
    bindir=src/network-workloads
else
    bindir="$bindir"/src
fi

"$bindir"/model-net-synthetic-slimfly --sync=1 -- "$srcdir"/src/network-workloads/conf/modelnet-synthetic-slimfly-min.conf
