#!/bin/bash

# Binaries generated by CMake are located in a different place
# to those of autoconf
if [ -z $GENERATED_USING_CMAKE ]; then
    bindir=src/network-workloads
else
    bindir="$bindir"/src
fi

mpirun -np 1 "$bindir"/model-net-synthetic --sync=1 --num_messages=1 -- "$srcdir"/src/network-workloads/conf/modelnet-synthetic-dragonfly.conf
