#!/bin/bash

# Binaries generated by CMake are located in a different place
# to those of autoconf
if [ -z $GENERATED_USING_CMAKE ]; then
    bin_dir=src/network-workloads
else
    bin_dir=src
fi

$bin_dir/model-net-synthetic --sync=1 --num_messages=1 -- $srcdir/src/network-workloads/conf/modelnet-synthetic-dragonfly.conf 
