noinst_PROGRAMS += \
 doc/example/example \
 doc/example_heterogeneous/example

bin_PROGRAMS += doc/example/tutorial-synthetic-ping-pong

doc_example_example_SOURCES = doc/example/example.c
doc_example_heterogeneous_example_SOURCES = doc/example_heterogeneous/example.c
doc_example_tutorial_synthetic_ping_pong_SOURCES = doc/example/tutorial-synthetic-ping-pong.c

EXTRA_DIST += \
 doc/BUILD_STEPS \
 doc/GETTING_STARTED \
 doc/RELEASE_NOTES \
 doc/acmsmall.cls \
 doc/algorithm.sty \
 doc/algorithmic.sty \
 doc/codes-best-practices.tex \
 doc/Makefile \
 doc/example/example.conf \
 doc/example/tutorial-ping-pong.conf \
 doc/example_heterogeneous/example.conf \
 doc/example_heterogeneous/example_torus.conf \
 doc/example_heterogeneous/README \
 doc/workload/example.kernel.txt \
 doc/workload/meta.txt
