lib_LIBRARIES += src/libcodes-net.a

EXTRA_DIST += \
 src/models/network-workloads/README_synthetic.txt \
 src/models/network-workloads/README_traces.txt \
 src/models/network-workloads/conf/modelnet-mpi-test.conf \
 src/models/network-workloads/conf/modelnet-mpi-test-cry-router.conf \
 src/models/network-workloads/conf/modelnet-mpi-test-dragonfly.conf \
 src/models/network-workloads/conf/modelnet-mpi-test-mini-fe.conf \
 src/models/network-workloads/conf/modelnet-mpi-test-torus.conf \
 src/models/networks/model-net/doc/README \
 src/models/networks/model-net/doc/README.dragonfly.txt \
 src/models/networks/model-net/doc/README.loggp.txt \
 src/models/networks/model-net/doc/README.simplenet.txt \
 src/models/networks/model-net/doc/README.simplep2p.txt \
 src/models/networks/model-net/MN_TODO


nobase_include_HEADERS = \
 codes/model-net.h	\
 codes/model-net-method.h \
 codes/model-net-lp.h \
 codes/model-net-sched.h \
 codes/net/dragonfly.h \
 codes/net/loggp.h \
 codes/net/simplenet-upd.h \
 codes/net/simplep2p.h \
 codes/net/torus.h

src_libcodes_net_a_SOURCES = \
 src/models/networks/model-net/model-net.c \
 src/models/networks/model-net/simplenet-upd.c \
 src/models/networks/model-net/torus.c \
 src/models/networks/model-net/dragonfly.c \
 src/models/networks/model-net/loggp.c \
 src/models/networks/model-net/simplep2p.c \
 src/models/networks/model-net/model-net-lp.c \
 src/models/networks/model-net/model-net-sched.c \
 src/models/networks/model-net/model-net-sched-impl.h \
 src/models/networks/model-net/model-net-sched-impl.c \
 src/models/network-workloads/model-net-mpi-wrklds.c \
 src/models/network-workloads/model-net-synthetic.c \
 src/models/network-workloads/model-net-dumpi-traces-dump.c

bin_PROGRAMS += src/models/network-workloads/model-net-mpi-wrklds
bin_PROGRAMS += src/models/network-workloads/model-net-dumpi-traces-dump
bin_PROGRAMS += src/models/network-workloads/model-net-synthetic

src_models_network_workloads_model_net_mpi_wrklds_SOURCES = src/models/network-workloads/model-net-mpi-wrklds.c
src_models_network_workloads_model_net_mpi_wrklds_LDADD = $(testlib) $(CODES_BASE_LIBS)
src_models_network_workloads_model_net_mpi_wrklds_LDFLAGS = $(CODES_BASE_LDFLAGS)
src_models_network_workloads_model_net_mpi_wrklds_CFLAGS = ${CODES_BASE_CFLAGS}

src_models_network_workloads_model_net_synthetic_SOURCES = src/models/network-workloads/model-net-synthetic.c
src_models_network_workloads_model_net_synthetic_LDADD = $(testlib) $(CODES_BASE_LIBS)
src_models_network_workloads_model_net_synthetic_LDFLAGS = $(CODES_BASE_LDFLAGS)
src_models_network_workloads_model_net_synthetic_CFLAGS = ${CODES_BASE_CFLAGS}

src_models_network_workloads_model_net_dumpi_traces_dump_SOURCES = src/models/network-workloads/model-net-dumpi-traces-dump.c
src_models_network_workloads_model_net_dumpi_traces_dump_LDADD = $(testlib) $(CODES_BASE_LIBS)
src_models_network_workloads_model_net_dumpi_traces_dump_LDFLAGS = $(CODES_BASE_LDFLAGS)
src_models_network_workloads_model_net_dumpi_traces_dump_CFLAGS = ${CODES_BASE_CFLAGS}

