#!/bin/bash

# Binaries generated by CMake are located in a different place
# to those of autoconf
if [ -z $GENERATED_USING_CMAKE ]; then
    bindir=tests/workload
else
    bindir=$bindir/tests
fi

"$bindir"/codes-workload-test --sync=1 "$srcdir"/tests/workload/codes-workload-test.conf
