#!/bin/bash

# Binaries generated by CMake are located in a different place
# to those of autoconf
if [ -z $GENERATED_USING_CMAKE ]; then
    bin_dir=tests/workload
else
    bin_dir=tests
fi

$bin_dir/codes-workload-test --sync=1 $srcdir/tests/workload/codes-workload-test.conf
